### ISSUE TITLE
Recursion error on completion

### ISSUE THREAD

**Issue by bo5o** [ncm2/ncm2-jedi#27] opened 2020-03-10 12:44 UTC
When you try to complete on a stdlib module, a recursion error occurs.

Minimal Example
=============

```python
import os

os.get<trigger completion>
```

Error traceback
============
```
...
[ncm2_jedi@yarp]     doc += name.py__doc__()
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/names.py", line 634, in py__doc__
[ncm2_jedi@yarp]     return _merge_name_docs(names)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/names.py", line 22, in _merge_name_docs
[ncm2_jedi@yarp]     doc += name.py__doc__()
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/names.py", line 236, in py__doc__
[ncm2_jedi@yarp]     return _merge_name_docs(names)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/names.py", line 22, in _merge_name_docs
[ncm2_jedi@yarp]     doc += name.py__doc__()
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/names.py", line 634, in py__doc__
[ncm2_jedi@yarp]     return _merge_name_docs(names)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/names.py", line 22, in _merge_name_docs
[ncm2_jedi@yarp]     doc += name.py__doc__()
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/names.py", line 236, in py__doc__
[ncm2_jedi@yarp]     return _merge_name_docs(names)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/names.py", line 22, in _merge_name_docs
[ncm2_jedi@yarp]     doc += name.py__doc__()
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/names.py", line 628, in py__doc__
[ncm2_jedi@yarp]     names = convert_names(names, prefer_stub_to_compiled=False)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/gradual/conversion.py", line 141, in convert_names
[ncm2_jedi@yarp]     names, prefer_stub_to_compiled=prefer_stub_to_compiled)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/utils.py", line 20, in wrapper
[ncm2_jedi@yarp]     return list(func(*args, **kwargs))
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/gradual/conversion.py", line 63, in _try_stub_to_python_names
[ncm2_jedi@yarp]     values = convert_values(name.infer(), ignore_compiled=prefer_stub_to_compiled)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/gradual/conversion.py", line 157, in convert_values
[ncm2_jedi@yarp]     for stub_value in values
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/common/value.py", line 32, in from_sets
[ncm2_jedi@yarp]     for set_ in sets:
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/gradual/conversion.py", line 157, in <genexpr>
[ncm2_jedi@yarp]     for stub_value in values
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/gradual/conversion.py", line 28, in _stub_to_python_value_set
[ncm2_jedi@yarp]     values = _infer_from_stub(stub_module_context, qualified_names, ignore_compiled)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/gradual/conversion.py", line 50, in _infer_from_stub
[ncm2_jedi@yarp]     non_stubs = non_stubs.py__getattribute__(name)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/base_value.py", line 395, in py__getattribute__
[ncm2_jedi@yarp]     return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/common/value.py", line 32, in from_sets
[ncm2_jedi@yarp]     for set_ in sets:
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/base_value.py", line 395, in <genexpr>
[ncm2_jedi@yarp]     return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/base_value.py", line 88, in py__getattribute__
[ncm2_jedi@yarp]     names = self.goto(name_or_str, name_context, analysis_errors)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/base_value.py", line 77, in goto
[ncm2_jedi@yarp]     names = finder.filter_name(filters, name_or_str)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/finder.py", line 36, in filter_name
[ncm2_jedi@yarp]     names = filter.get(string_name)
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/filters.py", line 240, in get
[ncm2_jedi@yarp]     return [n for filter in self._filters for n in filter.get(name)]
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/filters.py", line 240, in <listcomp>
[ncm2_jedi@yarp]     return [n for filter in self._filters for n in filter.get(name)]
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/filters.py", line 82, in get
[ncm2_jedi@yarp]     _get_definition_names(self._used_names, name),
[ncm2_jedi@yarp]   File "~/.pyenv/versions/py3nvim/lib/python3.7/site-packages/jedi/inference/filters.py", line 57, in _get_definition_names
[ncm2_jedi@yarp]     for_module = _definition_name_cache[used_names]
[ncm2_jedi@yarp]   File "~/.pyenv/versions/3.7.6/lib/python3.7/weakref.py", line 396, in __getitem__
[ncm2_jedi@yarp]     return self.data[ref(key)]
[ncm2_jedi@yarp] RecursionError: maximum recursion depth exceeded

```

health#jedi#check
========================================================================
##### jedi-vim version

 - jedi-vim git version: e83112f
 - jedi git submodule status:  3ad3dc08b8bf9d749b2d0d9fca038657711c82f2 pythonx/jedi (v0.16.0-11-g3ad3dc08)
 - parso git submodule status:  c864ca60d1a2f36524a4f79013a7de223e65e19d pythonx/parso (v0.6.0)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.executable: `~/.pyenv/versions/py3nvim/bin/python`
 - global sys.version: `3.7.6 (default, Jan 15 2020, 11:43:24), [GCC 7.4.0]`
 - global site module: `~/.pyenv/versions/3.7.6/lib/python3.7/site.py`

##### Jedi

 - path: `~/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.16.1

##### Jedi environment: <SameEnvironment: 3.7.6 in /home/bosdch1/.pyenv/versions/py3nvim>

 - executable: /home/bosdch1/.pyenv/versions/py3nvim/bin/python
 - sys_path:
    - `~/.pyenv/versions/3.7.6/lib/python37.zip`
    - `~/.pyenv/versions/3.7.6/lib/python3.7`
    - `~/.pyenv/versions/3.7.6/lib/python3.7/lib-dynload`
    - `~/.pyenv/versions/py3nvim/lib/python3.7/site-packages`

##### Known environments

 - <Environment: 3.6.9 in /usr> (/usr/bin/python3.6)

 - <Environment: 2.7.17 in /usr> (/usr/bin/python2.7)

##### Settings

```vim
g:jedi#goto_stubs_command = '' (default: '<leader>s')
g:jedi#usages_command = 'gr' (default: '<leader>n')
g:jedi#completions_command = '' (default: '<C-Space>')
g:jedi#rename_command = '<leader>rn' (default: '<leader>r')
g:jedi#goto_assignments_command = '' (default: '<leader>g')
g:jedi#goto_command = 'gd' (default: '<leader>d')
g:jedi#completions_enabled = 0 (default: 1)
```
health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: pyenv: Path: ~/.pyenv/libexec/pyenv
  - INFO: pyenv: Root: ~/.pyenv
  - INFO: Using: g:python_host_prog = "~/.pyenv/versions/py2nvim/bin/python"
  - INFO: Executable: ~/.pyenv/versions/py2nvim/bin/python
  - INFO: Python version: 2.7.16
  - INFO: pynvim version: 0.4.1
  - WARNING: Could not contact PyPI to get latest version.
  - ERROR: HTTP request failed: error: curl error with https://pypi.python.org/pypi/pynvim/json: 6

## Python 3 provider (optional)
  - INFO: pyenv: Path: ~/.pyenv/libexec/pyenv
  - INFO: pyenv: Root: ~/.pyenv
  - INFO: Using: g:python3_host_prog = "~/.pyenv/versions/py3nvim/bin/python"
  - INFO: Executable: ~/.pyenv/versions/py3nvim/bin/python
  - INFO: Python version: 3.7.6
  - INFO: pynvim version: 0.4.1
  - WARNING: Could not contact PyPI to get latest version.
  - ERROR: HTTP request failed: error: curl error with https://pypi.python.org/pypi/pynvim/json: 6

## Python virtualenv
  - OK: no $VIRTUAL_ENV

Output of `:version`
=================
```
NVIM v0.5.0-363-g31614d3eb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-pr
ototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/
travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/ho
me/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-42ac83d1-057a-458c-bd3f-e8353b2ab058

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"
```

**Comment by joncinque** [comment] 2020-03-26 10:34
I was having this issue too, looks like it was fixed on the jedi side in https://github.com/davidhalter/jedi/issues/1490 -- they haven't issued a new release recently, but the issue is resolved if you use the package directly from master:
```
pip3 install -e git://github.com/davidhalter/jedi.git#egg=jedi
```

**Closed as completed** 2020-03-27 10:35 UTC
